import { EmailRow } from '@/lib/types';

const DEMO_USER_ID = '00000000-0000-0000-0000-000000000001';

const baseTime = new Date('2024-05-17T08:00:00Z').getTime();

export const demoEmails: EmailRow[] = [
  {
    id: '00000000-0000-0000-0001-000000000001',
    user_id: DEMO_USER_ID,
    gmail_message_id: 'demo_msg_001',
    sender: 'alice@techcorp.com',
    subject: 'URGENT: Production API returning 500s',
    body: 'Our production environment has been returning 500 errors for the past 2 hours. All API endpoints are affected. We have 50,000 active users who cannot access the service. This is causing significant revenue loss. We need immediate assistance. Our engineering team has already tried restarting services but the issue persists. Please escalate this to your highest priority support tier immediately.',
    received_at: new Date(baseTime).toISOString(),
    category: 'Bug Report',
    priority: 'High',
    summary: 'Production API returning 500 errors for 2 hours affecting 50k users with revenue impact.',
    sentiment: 'Urgent',
    confidence: 0.97,
    escalation_risk: true,
    rationale: 'Production outage with revenue impact and large user base affected warrants immediate escalation.',
    processing_time_ms: 850,
    created_at: new Date(baseTime).toISOString(),
  },
  {
    id: '00000000-0000-0000-0001-000000000002',
    user_id: DEMO_USER_ID,
    gmail_message_id: 'demo_msg_002',
    sender: 'bob@enterprise.io',
    subject: 'Requesting full refund or we escalate legally',
    body: 'We have been a customer for 2 years and the service quality has deteriorated significantly. We are requesting a full refund of our annual subscription ($24,000). If this is not resolved within 48 hours, we will be forced to pursue legal action and file complaints with the relevant consumer protection agencies. We have documented all service failures and are prepared to present this evidence.',
    received_at: new Date(baseTime + 5 * 60000).toISOString(),
    category: 'Customer Complaint',
    priority: 'High',
    summary: 'Enterprise customer demanding $24k refund with legal escalation threat within 48 hours.',
    sentiment: 'Angry',
    confidence: 0.95,
    escalation_risk: true,
    rationale: 'Legal threat combined with significant refund demand requires immediate executive attention.',
    processing_time_ms: 920,
    created_at: new Date(baseTime + 5 * 60000).toISOString(),
  },
  {
    id: '00000000-0000-0000-0001-000000000003',
    user_id: DEMO_USER_ID,
    gmail_message_id: 'demo_msg_003',
    sender: 'sales@bigcorp.com',
    subject: 'Enterprise plan pricing for 500 seats',
    body: 'Hi, we are BigCorp with approximately 500 employees who would need access to your platform. We are currently evaluating several vendors and your product has made our shortlist. Could you please provide enterprise pricing for 500 seats? We are also interested in SSO integration, dedicated support, and custom SLA terms. Our budget cycle closes at the end of Q2, so we would need to make a decision within the next 3 weeks.',
    received_at: new Date(baseTime + 12 * 60000).toISOString(),
    category: 'Sales Inquiry',
    priority: 'High',
    summary: 'BigCorp requesting enterprise pricing for 500 seats with Q2 budget deadline in 3 weeks.',
    sentiment: 'Positive',
    confidence: 0.92,
    escalation_risk: false,
    rationale: 'High-value enterprise opportunity with imminent budget deadline requires prompt sales response.',
    processing_time_ms: 680,
    created_at: new Date(baseTime + 12 * 60000).toISOString(),
  },
  {
    id: '00000000-0000-0000-0001-000000000004',
    user_id: DEMO_USER_ID,
    gmail_message_id: 'demo_msg_004',
    sender: 'charlie@startup.dev',
    subject: 'Re: Re: Re: Still broken after 3 updates',
    body: 'This is absolutely unacceptable. I have been reporting this bug for 3 weeks now and it is STILL not fixed after 3 supposed updates. My entire workflow depends on the export feature and it has been broken this entire time. I have lost countless hours of productivity. If this is not fixed by end of week I am canceling my subscription and leaving a detailed review on every platform I can find. This is the worst support experience I have ever had.',
    received_at: new Date(baseTime + 18 * 60000).toISOString(),
    category: 'Bug Report',
    priority: 'High',
    summary: 'Customer reporting persistent export bug unresolved after 3 weeks and 3 updates, threatening cancellation.',
    sentiment: 'Furious',
    confidence: 0.94,
    escalation_risk: true,
    rationale: 'Long-standing unresolved bug with cancellation threat and public review warning requires immediate escalation.',
    processing_time_ms: 790,
    created_at: new Date(baseTime + 18 * 60000).toISOString(),
  },
  {
    id: '00000000-0000-0000-0001-000000000005',
    user_id: DEMO_USER_ID,
    gmail_message_id: 'demo_msg_005',
    sender: 'diana@agency.co',
    subject: 'Would love to see calendar integration',
    body: 'Hi team! Love the product so far. One feature that would make it even better for our agency workflow would be a calendar integration — specifically with Google Calendar and Outlook. It would be great to be able to schedule tasks directly from the dashboard. Not urgent at all, just wanted to share the feedback. Keep up the great work!',
    received_at: new Date(baseTime + 25 * 60000).toISOString(),
    category: 'Feature Request',
    priority: 'Low',
    summary: 'User requesting Google Calendar and Outlook integration for scheduling tasks from dashboard.',
    sentiment: 'Positive',
    confidence: 0.91,
    escalation_risk: false,
    rationale: 'Positive feature request with no urgency, suitable for product backlog consideration.',
    processing_time_ms: 520,
    created_at: new Date(baseTime + 25 * 60000).toISOString(),
  },
  {
    id: '00000000-0000-0000-0001-000000000006',
    user_id: DEMO_USER_ID,
    gmail_message_id: 'demo_msg_006',
    sender: 'angry@user.net',
    subject: 'Your product is garbage, canceling NOW',
    body: 'I cannot believe I wasted money on this garbage. Nothing works as advertised. The UI is confusing, the features are half-baked, and your support team takes days to respond. I am canceling my subscription RIGHT NOW and disputing the charge with my credit card company. I will be posting about this experience everywhere. Do NOT contact me trying to retain me — my mind is made up.',
    received_at: new Date(baseTime + 32 * 60000).toISOString(),
    category: 'Customer Complaint',
    priority: 'High',
    summary: 'Extremely angry customer canceling subscription and threatening chargeback and negative reviews.',
    sentiment: 'Furious',
    confidence: 0.96,
    escalation_risk: true,
    rationale: 'Chargeback threat combined with public review warning and immediate cancellation requires urgent retention response.',
    processing_time_ms: 870,
    created_at: new Date(baseTime + 32 * 60000).toISOString(),
  },
  {
    id: '00000000-0000-0000-0001-000000000007',
    user_id: DEMO_USER_ID,
    gmail_message_id: 'demo_msg_007',
    sender: 'finance@client.com',
    subject: "Invoice #4521 doesn't match our agreement",
    body: 'Hello, I am reviewing invoice #4521 dated May 15th and the amount ($3,450) does not match our agreed contract price of $2,800. Could you please review and send a corrected invoice? We have attached our signed contract for reference. We are happy to pay promptly once the invoice is corrected. Please let us know if you need any additional information.',
    received_at: new Date(baseTime + 40 * 60000).toISOString(),
    category: 'Billing',
    priority: 'Medium',
    summary: 'Invoice amount discrepancy of $650 vs agreed contract price, requesting corrected invoice.',
    sentiment: 'Neutral',
    confidence: 0.89,
    escalation_risk: false,
    rationale: 'Billing discrepancy is a routine issue requiring finance team review, no escalation needed.',
    processing_time_ms: 640,
    created_at: new Date(baseTime + 40 * 60000).toISOString(),
  },
  {
    id: '00000000-0000-0000-0001-000000000008',
    user_id: DEMO_USER_ID,
    gmail_message_id: 'demo_msg_008',
    sender: 'user@domain.com',
    subject: "Can't login since this morning",
    body: 'Hi support, I have been unable to log into my account since around 9am this morning. I keep getting an "Invalid credentials" error even though I am sure my password is correct. I tried resetting my password but the reset email is not arriving. I have checked my spam folder. My account email is user@domain.com. Please help as I need access for work.',
    received_at: new Date(baseTime + 48 * 60000).toISOString(),
    category: 'Bug Report',
    priority: 'Medium',
    summary: 'User unable to login since morning, password reset emails not arriving.',
    sentiment: 'Frustrated',
    confidence: 0.88,
    escalation_risk: false,
    rationale: 'Login issue affecting single user with no revenue impact, standard support resolution needed.',
    processing_time_ms: 700,
    created_at: new Date(baseTime + 48 * 60000).toISOString(),
  },
  {
    id: '00000000-0000-0000-0001-000000000009',
    user_id: DEMO_USER_ID,
    gmail_message_id: 'demo_msg_009',
    sender: 'bd@techcorp.io',
    subject: 'Partnership inquiry from TechCorp',
    body: 'Hello, I am the Business Development Manager at TechCorp. We are interested in exploring a potential technology partnership or reseller arrangement with your company. We serve over 2,000 SMB clients who could benefit from your solution. Would you be open to a 30-minute call to discuss potential synergies? I am available most days next week.',
    received_at: new Date(baseTime + 55 * 60000).toISOString(),
    category: 'Sales Inquiry',
    priority: 'Medium',
    summary: 'TechCorp BD manager seeking partnership or reseller arrangement serving 2000+ SMB clients.',
    sentiment: 'Positive',
    confidence: 0.87,
    escalation_risk: false,
    rationale: 'Partnership inquiry with significant reach potential, suitable for business development team follow-up.',
    processing_time_ms: 610,
    created_at: new Date(baseTime + 55 * 60000).toISOString(),
  },
  {
    id: '00000000-0000-0000-0001-000000000010',
    user_id: DEMO_USER_ID,
    gmail_message_id: 'demo_msg_010',
    sender: 'curious@user.com',
    subject: 'How do I export my data?',
    body: 'Hi, quick question — how do I export all my data from the platform? I want to create a backup. I looked through the settings but could not find an export option. Is this a feature that exists? If so, where can I find it? Thanks!',
    received_at: new Date(baseTime + 62 * 60000).toISOString(),
    category: 'General',
    priority: 'Low',
    summary: 'User asking how to export data for backup purposes, cannot find the option in settings.',
    sentiment: 'Neutral',
    confidence: 0.93,
    escalation_risk: false,
    rationale: 'Simple how-to question that can be resolved with documentation link or brief support response.',
    processing_time_ms: 480,
    created_at: new Date(baseTime + 62 * 60000).toISOString(),
  },
  {
    id: '00000000-0000-0000-0001-000000000011',
    user_id: DEMO_USER_ID,
    gmail_message_id: 'demo_msg_011',
    sender: 'cto@bigclient.com',
    subject: 'CRITICAL: Payment processing down for all users',
    body: 'CRITICAL ALERT: Our payment processing integration has been completely down for the past 45 minutes. ALL of our customers are unable to complete purchases. We are losing approximately $50,000 per hour in revenue. Our CTO and CEO are both aware and demanding immediate resolution. We need your senior engineering team on this NOW. This is a P0 incident for us. Please call me immediately at the number on file.',
    received_at: new Date(baseTime + 70 * 60000).toISOString(),
    category: 'Bug Report',
    priority: 'High',
    summary: 'Payment processing completely down for 45 minutes causing $50k/hour revenue loss, CTO and CEO involved.',
    sentiment: 'Critical',
    confidence: 0.99,
    escalation_risk: true,
    rationale: 'Massive revenue impact with executive involvement and quantified hourly losses demands immediate P0 response.',
    processing_time_ms: 810,
    created_at: new Date(baseTime + 70 * 60000).toISOString(),
  },
  {
    id: '00000000-0000-0000-0001-000000000012',
    user_id: DEMO_USER_ID,
    gmail_message_id: 'demo_msg_012',
    sender: 'happy@customer.com',
    subject: 'Thanks for the quick fix last week!',
    body: 'Hi team, just wanted to send a quick thank you for the fast resolution to the issue I reported last week. Your support team was incredibly responsive and the fix was deployed within hours. This is exactly the kind of service that keeps us as loyal customers. Please pass along my appreciation to the engineers who worked on it. Looking forward to continuing to use your product!',
    received_at: new Date(baseTime + 78 * 60000).toISOString(),
    category: 'General',
    priority: 'Low',
    summary: 'Customer expressing gratitude for quick bug fix resolution and praising support team responsiveness.',
    sentiment: 'Positive',
    confidence: 0.95,
    escalation_risk: false,
    rationale: 'Positive feedback email requiring only acknowledgment, no action needed.',
    processing_time_ms: 330,
    created_at: new Date(baseTime + 78 * 60000).toISOString(),
  },
];
